// src/scripts/generate-deploy-config.ts
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildCsp } from '../lib/seo';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const DIST_DIR = resolve(projectRoot, 'dist');

const ADMIN_CSP =
  "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net; img-src 'self' data: blob: https:; font-src 'self' https://unpkg.com https://cdn.jsdelivr.net; connect-src 'self' https://api.github.com https://unpkg.com https://cdn.jsdelivr.net; frame-src 'self' https://unpkg.com; manifest-src 'self';";

async function main() {
  const platform = process.argv.find((a) => a.startsWith('--platform='))?.split('=')[1];
  if (!platform) {
    console.error(
      '[generate-deploy-config] usage: --platform=cloudflare|vercel|netlify|github-pages',
    );
    process.exit(1);
  }
  const csp = buildCsp(process.env as never, { supportsHeaders: true });
  mkdirSync(DIST_DIR, { recursive: true });

  if (platform === 'cloudflare' || platform === 'netlify') {
    const headers = `/*\n  Content-Security-Policy: ${csp}\n  X-Frame-Options: SAMEORIGIN\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n\n/admin/*\n  Content-Security-Policy: ${ADMIN_CSP}\n`;
    writeFileSync(resolve(DIST_DIR, '_headers'), headers);
    console.log(`[generate-deploy-config] wrote dist/_headers (${platform})`);
  }

  if (platform === 'vercel') {
    const config: Record<string, unknown> = {};
    const existing = resolve(projectRoot, 'vercel.json');
    if (existsSync(existing))
      try {
        Object.assign(config, JSON.parse(readFileSync(existing, 'utf-8')));
      } catch {
        /* */
      }
    config.headers = [
      {
        source: '/(.*)',
        headers: [
          { key: 'Content-Security-Policy', value: csp },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
        ],
      },
      { source: '/admin/(.*)', headers: [{ key: 'Content-Security-Policy', value: ADMIN_CSP }] },
    ];
    writeFileSync(existing, JSON.stringify(config, null, 2) + '\n');
    console.log('[generate-deploy-config] wrote vercel.json');
  }

  if (platform === 'github-pages') {
    console.log('[generate-deploy-config] GitHub Pages uses <meta> CSP — no config file');
  }

  if (platform === 'nginx') {
    // 完整 server 块(IP/域名通用):try_files 兼容 trailingSlash 目录格式,
    // /_astro/ 哈希资源长缓存,404 页,/admin/ 独立 CSP(nginx add_header 非继承,需整组重写)
    const mainHeaders = [
      `  add_header Content-Security-Policy "${csp}" always;`,
      '  add_header X-Frame-Options "SAMEORIGIN" always;',
      '  add_header X-Content-Type-Options "nosniff" always;',
      '  add_header Referrer-Policy "strict-origin-when-cross-origin" always;',
      '  add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;',
    ].join('\n  ');
    const adminHeaders = [
      `  add_header Content-Security-Policy "${ADMIN_CSP}" always;`,
      '  add_header X-Frame-Options "SAMEORIGIN" always;',
      '  add_header X-Content-Type-Options "nosniff" always;',
      '  add_header Referrer-Policy "strict-origin-when-cross-origin" always;',
    ].join('\n  ');
    const conf = `# generated by generate:deploy-config -- --platform=nginx — do not edit
server {
  listen 80;
  listen [::]:80;
  server_name _;

  root /var/www/object920;
  index index.html;

  # redirects.json → 301(map 定义于 conf.d/object920-redirects.conf)
  if ($object920_redirect) {
    return 301 $object920_redirect;
  }

  gzip on;
  gzip_comp_level 5;
  gzip_types text/html text/css application/javascript application/json application/xml image/svg+xml;

${mainHeaders}

  location / {
    try_files $uri $uri/ =404;
  }

  # 带 content hash 的静态资源:永久缓存
  location /_astro/ {
${mainHeaders}
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location /pagefind/ {
${mainHeaders}
    add_header Cache-Control "public, max-age=86400";
  }

  # Sveltia CMS:独立 CSP,不继承主站(spec 8.5)
  location /admin/ {
${adminHeaders}
    try_files $uri $uri/ =404;
  }

  error_page 404 /404.html;
}
`;
    mkdirSync(resolve(DIST_DIR, 'nginx'), { recursive: true });
    writeFileSync(resolve(DIST_DIR, 'nginx', 'object920.conf'), conf);
    console.log('[generate-deploy-config] wrote dist/nginx/object920.conf');
  }
  console.log('[generate-deploy-config] done');
}
main().catch((err) => {
  console.error('[generate-deploy-config] error:', err);
  process.exit(1);
});
